name: autovideo2
region: sgp
services:
- name: web
  github:
    repo: apdue/ytauto
    branch: main
    deploy_on_push: true
  dockerfile_path: Dockerfile
  http_port: 5001
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "5001"
    scope: RUN_TIME
  - key: GOOGLE_CLIENT_ID
    value: ""
    scope: RUN_TIME
  - key: GOOGLE_CLIENT_SECRET
    value: ""
    scope: RUN_TIME
  - key: REDIRECT_URI
    value: ""
    scope: RUN_TIME

