name: autovideo2
region: sgp
services:
- name: web
  github:
    repo: apdue/ytauto
    branch: main
    deploy_on_push: true
  build_command: apt-get update && apt-get install -y ffmpeg && npm install && cd frontend && npm install && npm run build && cd ..
  run_command: node backend/server.js
  environment_slug: node-js
  http_port: 5001
  instance_count: 1
  instance_size_slug: basic-xxs
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "5001"
    scope: RUN_TIME
  - key: GOOGLE_CLIENT_ID
    value: ""
    scope: RUN_TIME
  - key: GOOGLE_CLIENT_SECRET
    value: ""
    scope: RUN_TIME
  - key: REDIRECT_URI
    value: ""
    scope: RUN_TIME

